apiVersion: v1
data:
  jdk.secstubs: |
    void java.io.PrintStream:println (java.lang.String) { -<~ }
    int java.lang.String:length () { -<~; return new(@) }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"jdk.secstubs":"void java.io.PrintStream:println (java.lang.String) { -\u003c~ }\nint java.lang.String:length () { -\u003c~; return new(@) }\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"symproto-policy","namespace":"symproto"}}
  creationTimestamp: "2026-07-23T15:03:27Z"
  name: symproto-policy
  namespace: symproto
  resourceVersion: "1500"
  uid: 0abf7946-6dd1-4243-bf75-34c78715d62d
